spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/exercicio-cliente-casa
    password: Sen@c2023
    username: clientecasa
    driverClassName: org.postgresql.Driver